- hosts: gosolar
  vars:
    selinux_mode: permissive
  vars_files:
    - credentials.vault
  roles:
    - selinux
  tasks:
    - include_vars: 
    - raw: dnf -y install python-dnf
    - dnf:
        name: "{{item}}"
      with_items:
        - docker
        - python-pip
        - libselinux-python
        - git
        - screen
        - haproxy

    - pip:
        name: 'git+https://github.com/docker/compose.git@1.5.2#egg=docker-compose'

    - git:
        repo: https://github.com/larsks/belmontgosolar-rt
        dest: /etc/gosolar

    - template:
        src: templates/docker-compose.override.yml
        dest: /etc/gosolar/docker-compose.override.yml
